apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: QQLQ-App
  namespace: argocd
spec:
  project: default
  
  destination:
    namespace: qqlq-app
    server: https://kubernetes.default.svc
  source:
    path: dev
    repoURL: https://github.com/HJHorst/argocd-app-config.git
    targetRevision: HEAD
  
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true