apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qqlq-app
  namespace: argocd
spec:
  project: default
  
  destination:
    namespace: qqlq-ns
    server: https://kubernetes.default.svc
  source:
    path: dev
    repoURL: https://github.com/HJHorst/argocd-app-config.git
    targetRevision: HEAD
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true