apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microservice
  name: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microservice
    spec:
      containers:
      - image: hjh/microservice-k8s
        name: microservice
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "768Mi"
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
      volumes:
        - name: config-volume
          configMap:
            name: microservice-properties
status: {}
